sudo: required
dist: trusty
language: node_js
services:
  - mongodb
node_js:
  # LTS version
  - "8.15.0"
cache:
  directories:
    - node_modules
install:
  - yarn
# command to run tests
script:
  - yarn test
after_script:
  - yarn coveralls
